### ISSUE TITLE
Application crashes in Android during swipe kill

### ISSUE THREAD

**Issue by DhirajMakane** [googlemaps/flutter-navigation-sdk#200]
Hi Team,
The application crashes during the swipe kill.

Steps to reproduce: 
1. Install and launch the application
2. And turn-by-turn navigation is not started.
3. Now swipe to kill the Android application.

**Stack Trace:**
com.google.maps.flutter.navigation.GoogleMapsNavigationSessionManager.getNavigator (GoogleMapsNavigationSessionManager.kt:151)
com.google.maps.flutter.navigation.GoogleMapsNavigationSessionManager.unregisterListeners (GoogleMapsNavigationSessionManager.kt:285)
com.google.maps.flutter.navigation.GoogleMapsNavigationSessionManager.onActivityDestroyed (GoogleMapsNavigationSessionManager.kt:139)
com.google.maps.flutter.navigation.GoogleMapsNavigationPlugin.onDetachedFromActivity (GoogleMapsNavigationPlugin.kt:78)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity (FlutterEngineConnectionRegistry.java:381)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach (FlutterActivityAndFragmentDelegate.java:747)
io.flutter.embedding.android.FlutterFragment.onDetach (FlutterFragment.java:1168)
androidx.fragment.app.Fragment.performDetach (Fragment.java:3386)
androidx.fragment.app.FragmentStateManager.detach (FragmentStateManager.java:850)
androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:349)
androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete (SpecialEffectsController.kt:664)
androidx.fragment.app.SpecialEffectsController$Operation.cancel (SpecialEffectsController.kt:507)
androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations (SpecialEffectsController.kt:293)
androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:3037)
androidx.fragment.app.FragmentManager.dispatchDestroy (FragmentManager.java:2988)
androidx.fragment.app.FragmentController.dispatchDestroy (FragmentController.java:346)
androidx.fragment.app.FragmentActivity.onDestroy (FragmentActivity.java:258)
**com.hero.vida.MainActivity.onDestroy (MainActivity.kt:444)**
android.app.Activity.performDestroy (Activity.java:9255)
android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1491)
android.app.ActivityThread.performDestroyActivity (ActivityThread.java:6232)
android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:6277)
android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:47)
android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:45)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:180)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:98)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2854)
android.os.Handler.dispatchMessage (Handler.java:108)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:328)
android.app.ActivityThread.main (ActivityThread.java:9242)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:594)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1099)

**Comment by Suryanarayana117** [comment]
i am also facing the issue and on app close navigation silent notification also not being killed why? can anyone help me with this issue?

**Comment by monfadev** [comment]
activity destroy have `unregisterListeners`, the func require init navigator. 

simply impl;

**Comment by Suryanarayana117** [comment]
> activity destroy have `unregisterListeners`, the func require init navigator.
> 
> simply impl
> 
> ```
> fun onActivityDestroyed() {
>     if (navigator != null) {
>       unregisterListeners()
>     }
>     weakActivity?.clear()
>     weakActivity = null
>     weakLifecycleOwner?.clear()
>     weakLifecycleOwner = null
>   }
> ```

I didn't get you? please explain me once

**Comment by Suryanarayana117** [comment]
> activity destroy have `unregisterListeners`, the func require init navigator.
> 
> simply impl
> 
> ```
> fun onActivityDestroyed() {
>     if (navigator != null) {
>       unregisterListeners()
>     }
>     weakActivity?.clear()
>     weakActivity = null
>     weakLifecycleOwner?.clear()
>     weakLifecycleOwner = null
>   }
> ```

how to call this function in flutter ?

**Comment by monfadev** [comment]
> > activity destroy have `unregisterListeners`, the func require init navigator.
> > simply impl
> > ```
> > fun onActivityDestroyed() {
> >     if (navigator != null) {
> >       unregisterListeners()
> >     }
> >     weakActivity?.clear()
> >     weakActivity = null
> >     weakLifecycleOwner?.clear()
> >     weakLifecycleOwner = null
> >   }
> > ```
> 
> how to call this function in flutter ?

you must fork the repo and then update

**Comment by Suryanarayana117** [comment]
com.google.maps.api.android.lib6.common.apiexception.ApiIllegalStateException: NavView.onPause cannot follow a NavView.onStop
E/PlatformViewsController(31717): 	at com.google.android.libraries.navigation.internal.aac.t.b(PG:2)
E/PlatformViewsController(31717): 	at com.google.android.libraries.navigation.NavigationView.onPause(PG:3)
E/PlatformViewsController(31717): 	at com.google.maps.flutter.navigation.GoogleMapsNavigationView.dispose(GoogleMapsNavigationView.kt:105)
E/PlatformViewsController(31717): 	at io.flutter.plugin.platform.PlatformViewsController$1.dispose(PlatformViewsController.java:254)
E/PlatformViewsController(31717): 	at io.flutter.plugin.platform.PlatformViewsController.diposeAllViews(PlatformViewsController.java:1072)
E/PlatformViewsController(31717): 	at io.flutter.plugin.platform.PlatformViewsController.onDetachedFromJNI(PlatformViewsController.java:943)
E/PlatformViewsController(31717): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:471)
E/PlatformViewsController(31717): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:765)
E/PlatformViewsController(31717): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:902)
E/PlatformViewsController(31717): 	at android.app.Activity.performDestroy(Activity.java:8665)
E/PlatformViewsController(31717): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1438)
E/PlatformViewsController(31717): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5728)
E/PlatformViewsController(31717): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5774)
E/PlatformViewsController(31717): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
E/PlatformViewsController(31717): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/PlatformViewsController(31717): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/PlatformViewsController(31717): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/PlatformViewsController(31717): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
E/PlatformViewsController(31717): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/PlatformViewsController(31717): 	at android.os.Looper.loopOnce(Looper.java:240)
E/PlatformViewsController(31717): 	at android.os.Looper.loop(Looper.java:351)
E/PlatformViewsController(31717): 	at android.app.ActivityThread.main(ActivityThread.java:8377)
E/PlatformViewsController(31717): 	at java.lang.reflect.Method.invoke(Native Method)
E/PlatformViewsController(31717): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/PlatformViewsController(31717): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
D/libMEOW (31717): meow delete tls: 0xb400007198649980
D/libMEOW (31717): meow delete tls: 0xb4000071b6ce4800
D/OplusScrollToTopManager(31717): unregisterGuidePopupDismissReceiverInSystemUI
D/OplusScrollToTopManager(31717): Receiver not registered: android.view.OplusScrollToTopManager$1@aa15938
D/OplusScrollToTopManager(31717): unregisterSystemUIBroadcastReceiver 
D/OplusScrollToTopManager(31717): java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@9323d11
V/ZoomWindowDecorView(31717): removeZoomView
W/FlutterJNI(31717): Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 67
W/FlutterJNI(31717): Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 68
W/FlutterJNI(31717): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: dev.flutter.pigeon.google_navigation_flutter.ViewEventApi.onNavigationUIEnabledChanged. Response ID: 56
i am getting this error when closing the application while in navigation ? navigation silent notification also not closing on application close

**Comment by Suryanarayana117** [comment]
What does it mean? I am not getting can you please explain a little more

**Comment by jokerttu** [comment]
@Suryanarayana117 the issue you have is not related to this, please see: https://github.com/googlemaps/flutter-navigation-sdk/issues/284

**Comment by jokerttu** [comment]
The fix for this will be deployed on next release: https://github.com/googlemaps/flutter-navigation-sdk/pull/272
